### Predict Attack Type ###

In [2]:
import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [3]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

In [4]:
# load dataset
dataframe = pandas.read_csv("input_attacktype.csv", header=None)
#dataframe = pandas.read_csv("test.csv", header=None)
dataframe = dataframe.dropna()
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

In [5]:
dataset.shape

(171378, 5)

In [6]:
print(dataset)

[[7 47 1 1.0 'Assassination']
 [0 116 6 0.0 'Hostage Taking (Kidnapping)']
 [1 140 9 1.0 'Assassination']
 ..., 
 [12 140 9 0.0 'Facility/Infrastructure Attack']
 [12 80 8 0.0 'Bombing/Explosion']
 [12 140 9 0.0 'Bombing/Explosion']]


In [7]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [18]:
print(dummy_y)

[[ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]]


In [8]:
X.shape

(171378, 4)

In [9]:
dummy_y.shape

(171378, 9)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, dummy_y, test_size=0.2)

In [11]:
X_train.shape

(137102, 4)

In [12]:
y_train.shape

(137102, 9)

In [13]:
X_test.shape

(34276, 4)

In [14]:
y_test.shape

(34276, 9)

In [17]:
print(X_train,
      y_train)

[[  12.  183.    5.    0.]
 [  11.  179.    9.    0.]
 [  10.  102.    5.    1.]
 ..., 
 [  11.   52.    1.    2.]
 [   3.   35.    7.    0.]
 [   2.  134.    8.    8.]] [[ 0.  0.  1. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]]


In [15]:
# create model
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(9, activation='softmax'))

In [16]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model.fit(X_train,y_train,epochs=20,batch_size=100)

Epoch 1/20
137102/137102 [==============================] - 2s - loss: 2.2731 - acc: 0.4561     
Epoch 2/20
137102/137102 [==============================] - 2s - loss: 1.4440 - acc: 0.4943     
Epoch 3/20
137102/137102 [==============================] - 3s - loss: 1.3879 - acc: 0.5077     
Epoch 4/20
137102/137102 [==============================] - 3s - loss: 1.3622 - acc: 0.5178     
Epoch 5/20
137102/137102 [==============================] - 2s - loss: 1.3519 - acc: 0.5195     
Epoch 6/20
137102/137102 [==============================] - 2s - loss: 1.3445 - acc: 0.5215     
Epoch 7/20
137102/137102 [==============================] - 3s - loss: 1.3404 - acc: 0.5243     
Epoch 8/20
137102/137102 [==============================] - 2s - loss: 1.3387 - acc: 0.5227     
Epoch 9/20
137102/137102 [==============================] - 2s - loss: 1.3339 - acc: 0.5230     
Epoch 10/20
137102/137102 [==============================] - 2s - loss: 1.3295 - acc: 0.5258     
Epoch 11/20
137102/137102 [==

In [18]:
score = model.evaluate(X_test,y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 1.2938666911
Test accuracy: 0.551843855759


In [19]:
from keras.layers import Dropout
# create model 2
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dropout(0.05))
model.add(Dense(30,activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(30,activation='relu'))
model.add(Dropout(0.05))
model.add(Dense(9, activation='softmax'))

In [20]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                50        
_________________________________________________________________
dropout_1 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 30)                330       
_________________________________________________________________
dropout_2 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 30)                930       
_________________________________________________________________
dropout_3 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 9)                 279       
Total para

In [21]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
history = model.fit(X_train,y_train,epochs=100,batch_size=100)

Epoch 1/100
137102/137102 [==============================] - 3s - loss: 1.7214 - acc: 0.4633     
Epoch 2/100
137102/137102 [==============================] - 3s - loss: 1.4328 - acc: 0.4917     
Epoch 3/100
137102/137102 [==============================] - 3s - loss: 1.3728 - acc: 0.4979     
Epoch 4/100
137102/137102 [==============================] - 3s - loss: 1.3472 - acc: 0.5079     
Epoch 5/100
137102/137102 [==============================] - 3s - loss: 1.3351 - acc: 0.5142     
Epoch 6/100
137102/137102 [==============================] - 3s - loss: 1.3248 - acc: 0.5239     
Epoch 7/100
137102/137102 [==============================] - 3s - loss: 1.3154 - acc: 0.5302     
Epoch 8/100
137102/137102 [==============================] - 3s - loss: 1.3100 - acc: 0.5345     
Epoch 9/100
137102/137102 [==============================] - 3s - loss: 1.3054 - acc: 0.5391     
Epoch 10/100
137102/137102 [==============================] - 3s - loss: 1.3006 - acc: 0.5417     
Epoch 11/100
137102

In [23]:
score = model.evaluate(X_test,y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 1.24764692718
Test accuracy: 0.573229081573
